# Generated by Django 4.1 on 2022-09-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='PersonModel',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_employee', to='accounts.personmodel'),
            preserve_default=False,
        ),
    ]
